routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\Auth\LoginController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middlware' => "auth"], function(){
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::group(['as' => "category.", 'prefix' => "category"], function(){
        Route::get('/',[CategoryController::class,'index'])->name('index');
        Route::get('/create',[CategoryController::class,'create'])->name('create');
        Route::post('/create',[CategoryController::class,'store'])->name('store');
        Route::get('/edit/{id}',[CategoryController::class,'edit'])->name('edit');
        Route::post('/edit/{id}',[CategoryController::class,'update'])->name('update');
        Route::any('/delete/{id}',[CategoryController::class,'delete'])->name('delete');
        Route::get('/search',[CategoryController::class,'search'])->name('search');
    });

    Route::group(['as' => "product.", 'prefix' => "products"], function(){
        Route::get('/',[ProductController::class,'index'])->name('index');
        Route::get('/create',[ProductController::class,'create'])->name('create');
        Route::post('/create',[ProductController::class,'store'])->name('store');
        Route::get('/edit/{id}',[ProductController::class,'edit'])->name('edit');
        Route::post('/edit/{id}',[ProductController::class,'update'])->name('update');
        Route::any('/delete/{id}',[ProductController::class,'delete'])->name('delete');
        Route::get('/search',[ProductController::class,'search'])->name('search');
        Route::get('/search/category',[ProductController::class,'categorySearch'])->name('category.search');
    });

});

Route::any('/logout',[LoginController::class,'logout'])->name('logout');

Auth::routes();

app/Models/Category.php
<?php

namespace App\Models;

use App\Models\Product;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'category_name',
        'category_desc',
    ];

    public function product(){
        return $this->hasMany(Product::class, 'category_id');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use DB;

class CategoryController extends Controller
{
    protected $data;

    public function index(){
        $this->data['categories'] = Category::orderBy('id')->get();

        return view('pages.category.index',$this->data);
    }

    public function create(){
        return view('pages.category.create');
    }

    public function store(CategoryRequest $request){
        $category = new Category();
        
        try {
            DB::beginTransaction();
            $category_name = $request->get('category_name');
            $category_desc = $request->get('category_desc');

            $category->category_name = $category_name;
            $category->category_desc = $category_desc;
            $category->save();

            DB::commit();
        } catch (\Throwable $e) {
            DB::rollback();
            return dd("error: ". $e);
        }

        return redirect()->route('category.index');
        
    }

    public function edit($id){
        $this->data['category'] = Category::where('id',$id)->first();
        return view('pages.category.edit',$this->data);
    }

    public function update(CategoryRequest $request, $id){
        $category = Category::where('id',$id)->first();
        
        try {
            DB::beginTransaction();
            $category_name = $request->get('category_name');
            $category_desc = $request->get('category_desc');

            $category->category_name = $category_name;
            $category->category_desc = $category_desc;
            $category->save();

            DB::commit();
        } catch (\Throwable $e) {
            DB::rollback();
            return dd("error: ". $e);
        }

        return redirect()->route('category.index');
        
    }

    public function delete($id){
        $category = Category::where('id',$id)->first();
        $category->delete();
        return redirect()->route('category.index');
    }

    public function search(Request $request){
        $category_name = $request->get('category_search');
        $category = Category::where('category_name','LIKE',$category_name)->first();

        if($category == null){
            $this->data['categories'] = array();
        }
        else{
            $this->data['categories'] = Category::where('id',$category->id)->get();
        }

        return view('pages.category.search',$this->data);
    }
}

resources/views/pages/category/create.blade.php
@extends('layouts.app')
@section('content')
<div class="content-container">
    <div class="content-title">
        <h3>Category</h3>

        <div class="content-navigation">
            <a href="{{route('home')}}">Home</a> / 
            <a href="{{route('category.index')}}">Category</a> / 
            Create
        </div>
    </div>
    <div class="content-form-container">
        <form action="" method="post">
            @csrf
            <div class="form-title">
                Add Category
            </div>
            <div class="form-input">
                <label for="category_name">Category Title</label>
                <input name="category_name" type="text" placeholder="Enter Category Title" value="{{old('category_name')}}">
                @if ($errors->has('category_name'))
                    <span class="text-danger">{{$errors->first()}}</span>
                @endif
            </div>
            <div class="form-input">
                <label for="category_desc">Product Details</label>
                <textarea name="category_desc" id="" cols="20" rows="5" placeholder="Enter Product Title" value="{{old('category_desc')}}"></textarea>
                @if ($errors->has('category_desc'))
                    <span class="text-danger">{{$errors->first()}}</span>
                @endif
            </div>
            <div class="form-button">
                <button type="submit">Submit</button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/pages/category/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="content-container">
    <div class="content-title">
        <h3>Category</h3>

        <div class="content-navigation">
            <a href="{{route('home')}}">Home</a> / 
            <a href="{{route('category.index')}}">Category</a> / 
            Edit
        </div>
    </div>
    <div class="content-form-container">
        <form action="" method="post">
            @csrf
            <div class="form-title">
                Edit Category
            </div>
            <div class="form-input">
                <label for="category_name">Category Title</label>
                <input name="category_name" type="text" placeholder="Enter Category Title" value="{{$category->category_name}}">
                @if ($errors->has('category_name'))
                    <span class="text-danger">{{$errors->first()}}</span>
                @endif
            </div>
            <div class="form-input">
                <label for="category_desc">Product Details</label>
                <textarea name="category_desc" id="" cols="20" rows="5" placeholder="Enter Product Title">{{$category->category_desc}}</textarea>
                @if ($errors->has('category_desc'))
                    <span class="text-danger">{{$errors->first()}}</span>
                @endif
            </div>
            <div class="form-button">
                <button type="submit">Submit</button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/pages/category/index.blade.php
@extends('layouts.app')
@section('content')
<div class="content-container">
    <div class="content-title">
        <span>Category</span>

        <div class="content-navigation">
            <a href="{{route('home')}}">Home</a> / Category
        </div>
    </div>
    <div class="create-button">
        <a href="{{route('category.create')}}">Create Category</a>
    </div>
    <div class="card">
              <div class="card-header">
                <h3 class="card-title">Categories Table</h3>
                <form action="{{route('category.search')}}">
                    @csrf
                    <input type="text" name="category_search" placeholder="Search Category">
                </form>
              </div>
              <!-- /.card-header -->
              <div class="card-body p-0">
                <table class="table table-striped">
                  <thead>
                    <tr>
                      <th style="width: 10px">#</th>
                      <th>Title</th>
                      <th>Description</th>
                      <th style="width: 40px">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    @forelse($categories as $category)
                    <tr>
                      <td>{{$category->id ? $category->id : 'Category Deleted'}}</td>
                      <td>{{$category->category_name ? $category->category_name : 'Category Deleted'}}</td>
                      <td>{{$category->category_desc ? $category->category_desc : 'Category Deleted'}}</td>
                      <td>
                        <a href="{{route('category.edit',$category->id)}}">Edit</a>
                        <a href="{{route('category.delete',$category->id)}}">Delete</a>
                      </td>
                    </tr>
                    @empty
                    <tr>
                      <td colspan="4" style="text-align:center">No Categories Yet</td>
                    </tr>
                    @endforelse
                  </tbody>
                </table>
              </div>
            </div>
</div>
@endsection

resources/views/pages/category/search.blade.php
@extends('layouts.app')
@section('content')
<div class="content-container">
    <div class="content-title">
        <span>Category</span>

        <div class="content-navigation">
            <a href="{{route('home')}}">Home</a> / Category
        </div>
    </div>
    <div class="create-button">
        <a href="{{route('category.create')}}">Create Category</a>
    </div>
    <div class="card">
              <div class="card-header">
                <h3 class="card-title">Categories Table</h3>
                <form action="{{route('category.search')}}">
                    @csrf
                    <input type="text" name="category_search" placeholder="Search Category">
                </form>
              </div>
              <!-- /.card-header -->
              <div class="card-body p-0">
                <table class="table table-striped">
                  <thead>
                    <tr>
                      <th style="width: 10px">#</th>
                      <th>Title</th>
                      <th>Description</th>
                      <th style="width: 40px">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    @forelse($categories as $category)
                    <tr>
                      <td>{{$category->id ? $category->id : 'Category Deleted'}}</td>
                      <td>{{$category->category_name ? $category->category_name : 'Category Deleted'}}</td>
                      <td>{{$category->category_desc ? $category->category_desc : 'Category Deleted'}}</td>
                      <td>
                        <a href="{{route('category.edit',$category->id)}}">Edit</a>
                        <a href="{{route('category.delete',$category->id)}}">Delete</a>
                      </td>
                    </tr>
                    @empty
                    <tr>
                      <td colspan="4" style="text-align:center">Category Not Found</td>
                    </tr>
                    @endforelse
                  </tbody>
                </table>
              </div>
            </div>
</div>
@endsection