routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\Auth\LoginController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middlware' => "auth"], function(){
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::group(['as' => "category.", 'prefix' => "category"], function(){
        Route::get('/',[CategoryController::class,'index'])->name('index');
        Route::get('/create',[CategoryController::class,'create'])->name('create');
        Route::post('/create',[CategoryController::class,'store'])->name('store');
        Route::get('/edit/{id}',[CategoryController::class,'edit'])->name('edit');
        Route::post('/edit/{id}',[CategoryController::class,'update'])->name('update');
        Route::any('/delete/{id}',[CategoryController::class,'delete'])->name('delete');
        Route::get('/search',[CategoryController::class,'search'])->name('search');
    });

    Route::group(['as' => "product.", 'prefix' => "products"], function(){
        Route::get('/',[ProductController::class,'index'])->name('index');
        Route::get('/create',[ProductController::class,'create'])->name('create');
        Route::post('/create',[ProductController::class,'store'])->name('store');
        Route::get('/edit/{id}',[ProductController::class,'edit'])->name('edit');
        Route::post('/edit/{id}',[ProductController::class,'update'])->name('update');
        Route::any('/delete/{id}',[ProductController::class,'delete'])->name('delete');
        Route::get('/search',[ProductController::class,'search'])->name('search');
        Route::get('/search/category',[ProductController::class,'categorySearch'])->name('category.search');
    });

});

Route::any('/logout',[LoginController::class,'logout'])->name('logout');

Auth::routes();

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\Category;

class Product extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'product_name',
        'product_desc',
        'cateogry_id',
        'image_path',
    ];

    public function category(){
        return $this->belongsTo(Category::class,'category_id');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Category;
use App\Models\Product;
use App\Http\Requests\ProductRequest;
use DB;

class ProductController extends Controller
{
    protected $data;

    public function index(){
        $this->data['products'] = Product::orderBy('id')->get();
        return view('pages.product.index',$this->data);
    }

    public function create(){
        $this->data['categories'] = Category::orderBy('id')->get();
        return view('pages.product.create',$this->data);
    }

    public function store(ProductRequest $request){
        $category = Category::where('id',$request->get('product_category'))->first();
        $product = new Product();
        try {
            
            $product_name = $request->get('product_name');
            $category_id = $request->get('product_category');
            $product_category = $category->category_name;
            $product_desc = $request->get('product_desc');
            $image_path = "images/".$product_category;
            $image_name = time().'.'.$request->file('product_image')->extension();
            
            $product->product_name = $product_name;
            $product->category_id = $category_id;
            $product->product_description = $product_desc;
            $product->image_path = $image_path."/".$image_name;
            $product->save();

            $request->file('product_image')->move(public_path($image_path),$image_name);

        } catch (\Throwable $th) {
            DB::rollback();
            return dd("error: Upload Failed");
        }

        return redirect()->route('product.index');
    }

    public function edit($id){
        $this->data['categories'] = Category::orderBy('id')->get();
        $this->data['product'] = Product::where('id',$id)->first();
        return view('pages.product.edit',$this->data);
    }

    public function update(ProductRequest $request, $id){
        $category = Category::where('id',$request->get('product_category'))->first();
        $product =  Product::where('id',$id)->first();
        try {
            
            $product_name = $request->get('product_name');
            $category_id = $request->get('product_category');
            $product_category = $category->category_name;
            $product_desc = $request->get('product_desc');
            $image_path = "images/".$product_category;
            $image_name = time().'.'.$request->file('product_image')->extension();
            
            $product->product_name = $product_name;
            $product->category_id = $category_id;
            $product->product_description = $product_desc;
            $product->image_path = $image_path."/".$image_name;
            $product->save();

            $request->file('product_image')->move(public_path($image_path),$image_name);

        } catch (\Throwable $th) {
            DB::rollback();
            return dd("error: Upload Failed");
        }

        return redirect()->route('product.index');
    }

    public function delete($id){
        $product = Product::where('id',$id)->get();
        $product->delete();
        return redirect()->route('product.index');
    }

    public function search(Request $request){
        $product_name = $request->get('search');
        $this->data['products'] = Product::where('product_name','LIKE','%'.$product_name.'%')->get();

        return view('pages.product.search',$this->data);
    }

    public function categorySearch(Request $request){
        $category_name = $request->get('category_search');
        $category = Category::where('category_name','LIKE',$category_name)->first();
        
        if($category == null){
            $this->data['products'] = array();
        }
        else{
            $this->data['products'] = Product::where('category_id',$category->id)->get();
        }

        return view('pages.product.search',$this->data);
    }
}

resources/views/pages/product/create.blade.php
@extends('layouts.app')
@section('content')
<div class="content-container">
    <div class="content-title">
        <h3>Product</h3>

        <div class="content-navigation">
            <a href="{{route('home')}}">Home</a> / 
            <a href="{{route('product.index')}}">Product</a> / 
            Create
        </div>
    </div>
    <div class="content-form-container">
        <form action="" method="post" enctype="multipart/form-data">
            @csrf
            <div class="form-title">
                Add Product
            </div>
            <div class="form-input">
                <label for="product_category">Product name</label>
                <select name="product_category" id="">
                    <option value="" selected disabled>Select Category</option>
                    @forelse($categories as $category)
                    <option value="{{$category->id}}">{{$category->category_name}}</option>
                    @empty
                    <option value="" disabled>No Categories</option>
                    @endforelse
                </select> 
                @if ($errors->has('product_category'))
                    <span class="text-danger">{{$errors->first()}}</span>
                @endif
            </div>
            <div class="form-input">
                <label for="product_name">Product name</label>
                <input name="product_name" type="text" placeholder="Enter Product Title">
                @if ($errors->has('product_name'))
                    <span class="text-danger">{{$errors->first()}}</span>
                @endif
            </div>
            <div class="form-input">
                <label for="product_desc">Product Details</label>
                <textarea name="product_desc" id="" cols="20" rows="5" placeholder="Enter Product Title"></textarea>
                @if ($errors->has('product_desc'))
                    <span class="text-danger">{{$errors->first()}}</span>
                @endif
            </div>
            <div class="form-input">
                <label for="product_image">Product Image</label>
                <input name="product_image" type="file">
                @if ($errors->has('product_image'))
                    <span class="text-danger">{{$errors->first()}}</span>
                @endif
            </div>
            <div class="form-button">
                <button type="submit">Submit</button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/pages/product/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="content-container">
    <div class="content-title">
        <h3>Product</h3>

        <div class="content-navigation">
            <a href="{{route('home')}}">Home</a> / 
            <a href="{{route('product.index')}}">Product</a> / 
            Edit
        </div>
    </div>
    <div class="content-form-container">
        <form action="" method="post" enctype="multipart/form-data">
            @csrf
            <div class="form-title">
                Edit Product
            </div>
            <div class="form-input">
                <label for="product_category">Product name</label>
                <select name="product_category" id="">
                    <option value="" selected disabled>Select Category</option>
                    @forelse($categories as $category)
                    <option value="{{$category->id}}">{{$category->category_name}}</option>
                    @empty
                    <option value="" disabled>No Categories</option>
                    @endforelse
                </select> 
                @if ($errors->has('product_category'))
                    <span class="text-danger">{{$errors->first()}}</span>
                @endif
            </div>
            <div class="form-input">
                <label for="product_name">Product name</label>
                <input name="product_name" type="text" placeholder="Enter Product Title" value="{{$product->product_name}}">
                @if ($errors->has('product_name'))
                    <span class="text-danger">{{$errors->first()}}</span>
                @endif
            </div>
            <div class="form-input">
                <label for="product_desc">Product Details</label>
                <textarea name="product_desc" id="" cols="20" rows="5" placeholder="Enter Product Title">{{$product->product_description}}</textarea>
                @if ($errors->has('product_desc'))
                    <span class="text-danger">{{$errors->first()}}</span>
                @endif
            </div>
            <div class="form-input">
                <label for="product_image">Product Image</label>
                <input name="product_image" type="file">
                @if ($errors->has('product_image'))
                    <span class="text-danger">{{$errors->first()}}</span>
                @endif
            </div>
            <div class="form-button">
                <button type="submit">Submit</button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/pages/product/index.blade.php
@extends('layouts.app')
@section('content')
<div class="content-container">
    <div class="content-title">
        <span>Product</span>

        <div class="content-navigation">
            <a href="{{route('home')}}">Home</a> / Product
        </div>
    </div>
    <div class="create-button">
        <a href="{{route('product.create')}}">Create Product</a>
    </div>
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">Products Table</h3>
        <form action="{{route('product.category.search')}}">
            @csrf
            <input type="text" name="category_search" placeholder="Search Category">
        </form>
      </div>
      <!-- /.card-header -->
      <div class="card-body p-0">
        <table class="table table-striped">
          <thead>
            <tr>
              <th style="width: 10px">#</th>
              <th>Image</th>
              <th>Title</th>
              <th>Description</th>
              <th>Category</th>
              <th style="width: 40px">Action</th>
            </tr>
          </thead>
          <tbody>
            @forelse($products as $product)
            <tr class="product-tr">
              <td>{{$product->id}}</td>
              <td>
                <img src="{{asset($product->image_path ? $product->image_path : null)}}" height="50px" alt="{{$product->image_path ? $product->image_path : null}}">
              </td>
              <td>{{$product->product_name ? $product->product_name : 'Deleted'}}</td>
              <td>{{$product->product_description ? $product->product_description : 'Deleted'}}</td>
              <td>{{$product->category->category_name ? $product->category->category_name : 'Deleted'}}</td>
              <td>
                <a href="{{route('product.edit',$product->id)}}">Edit</a>
                <a href="{{route('product.delete',$product->id)}}">Delete</a>
              </td>
            </tr>
            @empty
            <tr>
              <td colspan="6" style="text-align:center">No Products Yet</td>
            </tr>
            @endforelse
          </tbody>
        </table>
      </div>
    </div>
</div>
@endsection

resources/views/pages/product/search.blade.php
@extends('layouts.app')
@section('content')
<div class="content-container">
    <div class="content-title">
        <span>Product</span>

        <div class="content-navigation">
            <a href="{{route('home')}}">Home</a> / Product
        </div>
    </div>
    <div class="create-button">
        <a href="{{route('product.create')}}">Create Product</a>
    </div>
    <div class="card">
        <div class="card-header">
        <h3 class="card-title">Products Table</h3>
        <form action="{{route('product.category.search')}}">
            @csrf
            <input type="text" name="category_search" placeholder="Search Category">
        </form>
        </div>
        <!-- /.card-header -->
        <div class="card-body p-0">
        <table class="table table-striped">
            <thead>
            <tr>
                <th style="width: 10px">#</th>
                <th>Image</th>
                <th>Title</th>
                <th>Description</th>
                <th>Category</th>
                <th style="width: 40px">Action</th>
            </tr>
            </thead>
            <tbody>
            @forelse($products as $product)
            <tr class="product-tr">
                <td>{{$product->id}}</td>
                <td>
                <img src="{{asset($product->image_path ? $product->image_path : null)}}" height="50px" alt="{{$product->image_path ? $product->image_path : null}}">
                </td>
                <td>{{$product->product_name ? $product->product_name : 'Deleted'}}</td>
                <td>{{$product->product_description ? $product->product_description : 'Deleted'}}</td>
                <td>{{$product->category->category_name ? $product->category->category_name : 'Deleted'}}</td>
                <td>
                <a href="{{route('product.edit',$product->id)}}">Edit</a>
                <a href="{{route('product.delete',$product->id)}}">Delete</a>
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="6" style="text-align:center">No Products</td>
            </tr>
            @endforelse
            </tbody>
        </table>
        </div>
    </div>
</div>
@endsection